version: '3.4'
services:
  image_processor:
    image: themasteredpanda/tldr-image-processor:latest
    container_name: tldr-image-processor
    ports:
      - "5000:5000"

networks:
  default:
    external:
      name: tldr-net
